[package]
name = "yolotrader_server"
version = "1.0.0"
authors = ["Eric Semeniuc <3838856+esemeniuc@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.5", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
juniper = "0.14.2"
rust-embed= "5.5.1"

async-graphql = "1.15.6"
async-graphql-actix-web = "1.14.14"
actix-web = { version = "2.0.0", features=["rustls"] }
actix-rt = "1.1.1"
actix-web-actors = "2.0.0"
slab = "0.4.2"
tokio = { version = "0.2.21", features = ["time", "stream"] }
futures = "0.3.5"

actix = "0.9.0"
actix-cors = "0.2.0"
actix-web-httpauth = "0.4.1"
mime_guess = "2.0.3"
chrono = { version = "0.4.11", features = ["serde"] }
jsonwebtoken = "7.1.1"
serde = { version = "1.0.111", features = ["derive"] }
names = "0.11.0"
serde_json = "1.0.55"
rand = "0.7.3"
clap = "2.33.1"
