[package]
name = "yolotrader_server"
version = "1.0.0"
authors = ["Eric Semeniuc <3838856+esemeniuc@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.5", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
juniper = "0.14.2"
rust-embed= "5.6.0"
log = "0.4.11"
env_logger = "0.7.1"

async-graphql = "2.0.0-alpha.18"
async-graphql-actix-web = "2.0.0-alpha.18"
actix-web = { version = "3.0.2", features = ["rustls"] }
actix-rt = "1.1.1"
actix-web-actors = "3.0.0"
slab = "0.4.2"
tokio = { version = "0.2.22", features = ["time", "stream"] }
futures = "0.3.5"
futures-util = "0.3.5"

actix = "0.10.0"
actix-cors = "0.3.0"
actix-web-httpauth = "0.5.0"
mime_guess = "2.0.3"
chrono = { version = "0.4.18", features = ["serde"] }
jsonwebtoken = "7.2.0"
serde = { version = "1.0.116", features = ["derive"] }
names = "0.11.0"
serde_json = "1.0.57"
rand = "0.7.3"
clap = "2.33.3"
web-push = "0.7.2"
base64 = "0.12.3"
