[package]
name = "yolotrader_server"
version = "1.0.0"
authors = ["Eric Semeniuc <3838856+esemeniuc@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.4", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
juniper = "0.14.2"
rust-embed= "5.5.1"

async-graphql = "1.12.17"
async-graphql-actix-web = "1.4.17"
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-web-actors = "2.0.0"
slab = "0.4.2"
tokio = { version = "0.2", features = ["time", "stream"] }
futures = "0.3.0"

actix-cors = "0.2.0"
actix-web-httpauth = "0.4.1"
mime_guess = "2.0.3"
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "7"
serde = {version = "1.0", features = ["derive"] }
names = "0.11.0"
serde_json = "1.0.51"
rand = "0.7.3"
clap = "2.33.1"