[package]
name = "yolotrader_server"
version = "1.0.0"
authors = ["Eric Semeniuc <3838856+esemeniuc@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
sqlx = { version = "0.4.0-beta.1", features = [ "macros", "sqlite", "chrono", "migrate" ] }
#sqlx = { version = "0.4.0-beta.1", default-features = false, features = [ "runtime-tokio", "macros", "sqlite", "chrono" ] }
rust-embed= "5.6.0"
log = "0.4.11"
env_logger = "0.8.1"

async-graphql = "2.0.4"
async-graphql-actix-web = "2.0.4"
actix-web = { version = "3.1.0", features = ["rustls"] }
actix-web-actors = "3.0.0"
tokio = { version = "0.3.0", features = ["time", "stream"] }
futures = "0.3.6"
futures-util = "0.3.6"

actix = "0.10.0"
actix-cors = "0.4.1"
async-stream = "0.3.0"
mime_guess = "2.0.3"
chrono = { version = "0.4.19", features = ["serde"] }
jsonwebtoken = "7.2.0"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
rand = "0.7.3"
clap = "2.33.3"
web-push = "0.7.2"
base64 = "0.13.0"
