query getOptionChain($ticker:String!, $expiration:String!, $strategy:OptionStrategy!) {
  optionQuote: getOptionChain(ticker:$ticker, expiration:$expiration, strategy:$strategy){
    optionType,
    strike, expiration, bid, ask, last, delta, 
    gamma, theta, vega, rho, volatility, timeValue
  }
}
