mutation SignupMutation(
  $firstName: String!
  $lastName: String!
  $email: String!
  $password: String!
) {
  signup(
    firstName: $firstName
    lastName: $lastName
    email: $email
    password: $password
  )
}